core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:Order:index }

core_orderInfo:
    path:    /orderInfo
    defaults: { _controller: CoreBundle:Order:orderInfo }

core_ticketsInfo:
    path:    /ticketsInfo
    defaults: { _controller: CoreBundle:Order:ticketsInfo }

core_payment:
    path:    /payment
    defaults: { _controller: CoreBundle:Order:payment }

core_confirm:
    path:    /confirm
    defaults: { _controller: CoreBundle:Order:confirm }

core_error:
    path:    /error/{retry}
    defaults: { _controller: CoreBundle:Order:error, retry: "false" }
