parameters:
    tarif_normal: 16
    tarif_senior: 12
    tarif_reduit: 10
    tarif_enfant: 8

services:
    core.setprice:
        class: CoreBundle\SetPrice\SetPrice
        arguments:
            - "%tarif_normal%"
            - "%tarif_senior%"
            - "%tarif_reduit%"
            - "%tarif_enfant%"
