parameters:
    normal_fare: 16
    senior_fare: 12
    reduced_fare: 10
    child_fare: 8
    max_tickets_per_day: 1000  # Nombre de tickets maximum vendus par jour

services:
    core.setprice:
        class: CoreBundle\SetPrice\SetPrice
        arguments:
            - "%normal_fare%"
            - "%senior_fare%"
            - "%reduced_fare%"
            - "%child_fare%"

    commande.listener:
        class: CoreBundle\EventListener\sendTickets
        arguments:
            - "@mailer"
            - "@templating"
            - "@knp_snappy.pdf"
            - "%mailer_user%"
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    core.museum_not_full_validator:
            class: CoreBundle\Validator\MuseumNotFullValidator
            arguments:
                - "@doctrine.orm.entity_manager"
                - "%max_tickets_per_day%"
            tags:
                - { name: validator.constraint_validator }