# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    tickets_max_jour: 1000  # Nombre de tickets maximum vendus par jour

services:
    core.museum_not_full_validator:
        class: CoreBundle\Validator\MuseumNotFullValidator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%tickets_max_jour%"
        tags:
            - { name: validator.constraint_validator }
