<?php

namespace CoreBundle\Repository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository
{
    // Méthode récupérant le nombre de billets vendus pour une date donnée
    public function sumTicketsSold(\DateTime $date)
    {
        $qb = $this->createQueryBuilder('ord');
        return $qb->add('where', $qb->expr()->eq('ord.dateVisit', ':visit_date_typed'))
            ->setParameter('visit_date_typed', $date, \Doctrine\DBAL\Types\Type::DATETIME)
            ->select('SUM(ord.ticketsNb) as totalTickets')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
